### ISSUE TITLE
Out of the box

### ISSUE THREAD

**Issue by itali43** [chriswebb09/ARKitNavigationDemo#1]
Hey, this is awesome, was wondering if the demo works out-of-the-box or needs some love via the tutorials?   I've changed the destination location to a location near me, but it hasn't conjured up dots and directions.
Thanks, will be absorbing the code, tutorials have been easy to follow

**Comment by chriswebb09** [comment]
Hi! Thanks so much, I appreciate the feedback! I've been meaning to write up a decent readme. So it does work out of the box assuming you've entered the right coordinates and whatnot. After you hit go, you have to tap the screen. I had to set the nodes to static, otherwise the GPS signal tends to make them jump around. So it'll refine the position for 8 cycles I think, then set them to static. So, if the permissions are right for location tracking, hit go, and then tap the screen when the next screen appears.

**Comment by itali43** [comment]
Ok, used an earlier version and got to the right first screen ( with the go button) but now ending up in the Start.storyboard first.  Also haven't found the place to set destination location in this iteration.  Went back to previous and have it in ViewController.setupNavigation() but I'm fairly sure I put it there

only two things I'm thinking may have been the problem yesterday is that I may not of waited the few seconds, and I'm using it indoors which tends to make location slower (I think)

**Comment by chriswebb09** [comment]
Yeah, GPS indoor is a lot less reliable. I would try it outside, but it should render regardless. It's not instantaneous, so it might just be expecting it to render too quickly.
In the older version there should be this: 
 ` locationService.startUpdatingLocation()
        destinationLocation = CLLocationCoordinate2D(latitude: 40.736248, longitude: -73.979397)
        
        if destinationLocation != nil {
            navigationService.getDirections(destinationLocation: destinationLocation, request: MKDirectionsRequest()) { steps in
                for step in steps {
                    self.annons.append(POIAnnotation(point: PointOfInterest(name: "N " + String(describing: step.instructions), coordinate: step.getLocation().coordinate)))
                }
                self.steps.append(contentsOf: steps)
            }
        }`
As long as the second screen has loaded it should work.  One solution is to go outside and choose a destination that is directly in front of you, like 2 or three blocks away.

**Comment by itali43** [comment]
Ok thanks, I'll try that now, I have a sneaking feeling it's due to being inside!

**Comment by chriswebb09** [comment]
No worries! I would try giving it a few extra seconds to render, and b, have a good idea of where the bubbles are rendering. You'll look a bit weird out on the street doing this, but try looking around to make sure the bubbles are appearing.

**Comment by itali43** [comment]
It worked!!! Definitely b/c of not being outside.  Additionally it's popping me down a to the lower street on the hill that i'm on so that the graphics are tougher to see!

Was SO puzzled, thank you so much for the help troubleshooting!

**Comment by chriswebb09** [comment]
Awesome! I'm so glad to hear it. No worries, I'm happy I could help!
