### ISSUE TITLE
Position Node in a specific GPS Coordinate ?

### ISSUE THREAD

**Issue by omarojo** [chriswebb09/ARKitNavigationDemo#7]
HI, I stumbled upon your tutorials. 
Im looking for a straightforward solution to place 3D objects in specific gps coordinates. That's all. 

So I can place a 3d sculptures in multiple locations that look like they standing on the floor and you can walk around them. Is there a specific piece of code I can use from your project?

**Comment by chriswebb09** [comment]
Hi! Yeah, no worries! There is but I would direct you to this project just because it tailored specifically for locations https://github.com/ProjectDent/ARKit-CoreLocation. If that isn't what you're looking for let me know, and I can pull out the location code directly and send it over.
